### ISSUE TITLE
Renaming a journal should refresh the main page.

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#39] opened 2018-11-07 15:24 UTC
Currently it doesn't, and clicking the old outdated name of the journal will open the last journal on the list.

**Comment by sorentycho** [comment] 2018-11-07 19:03
This is that damnable file watching path bug again, I'm sure of it. I pushed a commit with some additional debug output and a possible fix. If it's not working now, can you past me the full console output from the main page after an attempt?

**Comment by SparksJ2** [comment] 2018-11-09 02:33
```C:\users\sparks\projects\blackmirror\lib\common.js:166 Opening appLink: rename:C:/Users/sparks/conversations/thedeeps2
C:\users\sparks\projects\blackmirror\lib\common.js:627 Renaming C:/Users/sparks/conversations/thedeeps2 thedeeps3
2C:\users\sparks\projects\blackmirror\node_modules\snapdragon\lib\parser.js:473 Uncaught Error: no parsers registered for: "][RT]"
    at parse (C:\users\sparks\projects\blackmirror\node_modules\snapdragon\lib\parser.js:473)
    at Parser.parse (C:\users\sparks\projects\blackmirror\node_modules\snapdragon\lib\parser.js:477)
    at Snapdragon.parse (C:\users\sparks\projects\blackmirror\node_modules\snapdragon\index.js:122)
    at Snapdragon.<anonymous> (C:\users\sparks\projects\blackmirror\node_modules\braces\lib\braces.js:40)
    at Braces.parse (C:\users\sparks\projects\blackmirror\node_modules\braces\lib\braces.js:66)
    at Braces.expand (C:\users\sparks\projects\blackmirror\node_modules\braces\lib\braces.js:87)
    at create (C:\users\sparks\projects\blackmirror\node_modules\braces\index.js:142)
    at memoize (C:\users\sparks\projects\blackmirror\node_modules\braces\index.js:298)
    at Function.braces.create (C:\users\sparks\projects\blackmirror\node_modules\braces\index.js:165)
    at Function.braces.expand (C:\users\sparks\projects\blackmirror\node_modules\braces\index.js:81)
parse @ C:\users\sparks\projects\blackmirror\node_modules\snapdragon\lib\parser.js:473
parse @ C:\users\sparks\projects\blackmirror\node_modules\snapdragon\lib\parser.js:477
Snapdragon.parse @ C:\users\sparks\projects\blackmirror\node_modules\snapdragon\index.js:122
(anonymous) @ C:\users\sparks\projects\blackmirror\node_modules\braces\lib\braces.js:40
Braces.parse @ C:\users\sparks\projects\blackmirror\node_modules\braces\lib\braces.js:66
Braces.expand @ C:\users\sparks\projects\blackmirror\node_modules\braces\lib\braces.js:87
create @ C:\users\sparks\projects\blackmirror\node_modules\braces\index.js:142
memoize @ C:\users\sparks\projects\blackmirror\node_modules\braces\index.js:298
braces.create @ C:\users\sparks\projects\blackmirror\node_modules\braces\index.js:165
braces.expand @ C:\users\sparks\projects\blackmirror\node_modules\braces\index.js:81
getDirParts @ C:\users\sparks\projects\blackmirror\node_modules\chokidar\index.js:435
(anonymous) @ C:\users\sparks\projects\blackmirror\node_modules\chokidar\index.js:452
(anonymous) @ C:\users\sparks\projects\blackmirror\node_modules\readdirp\readdirp.js:226
(anonymous) @ C:\users\sparks\projects\blackmirror\node_modules\readdirp\readdirp.js:226
(anonymous) @ C:\users\sparks\projects\blackmirror\node_modules\readdirp\readdirp.js:199
(anonymous) @ C:\users\sparks\projects\blackmirror\node_modules\graceful-fs\polyfills.js:287
(anonymous) @ fs.js:183

**Comment by sorentycho** [comment] 2018-11-09 04:06
Looks like this is probably https://github.com/paulmillr/chokidar/issues/699

**Comment by sorentycho** [comment] 2018-11-09 08:29
Confirmed. Having a filename containing square brackets kills chokidar.

**Comment by sorentycho** [comment] 2018-11-09 10:16
Fixed by switching to just watching dirs with no globs.

**Closed by sorentycho** 2018-11-09 10:16 UTC
Labels: bug
